Added files discovery method
sabaubogdan/scribe pull request #1
Opened 2018-01-14 12:35 UTC by sabaubogdan

2018-01-14 12:37 UTC, sabaubogdan commented
.

2018-01-14 17:50 UTC, sabaudragos requested changes

2018-01-14 17:50 UTC, Callin commented on src/main/java/xyz/vegaone/scribe/service/FileDiscoveryServiceImpl.java
> +    public static void main(String[] args) {
The `main()` method should be removed. It's used only for testing purposes

2018-01-14 17:50 UTC, Callin commented on src/main/java/xyz/vegaone/scribe/service/FileDiscoveryServiceImpl.java
> +            System.out.println(e.getMessage());
We need a logger here. Please add one on the class `@Slf4j` and then log here a message like `log.error('Error while discovering files', e)`

2018-01-14 17:50 UTC, Callin commented on src/main/java/xyz/vegaone/scribe/service/FileDiscoveryServiceImpl.java
> +        Map<String, List<String>> foundFiles = new HashMap<>();
A more appropriate name would be `filePathsFound`

2018-01-14 17:50 UTC, Callin commented on src/main/java/xyz/vegaone/scribe/service/FileDiscoveryServiceImpl.java
> +                    if (filePath.toString().endsWith("txt")) {
A good practice is to not use text directly into code. A better approach is to define constants at the class level and then use those constants int the code. 
e.g. 
```java
private static final String TEXT_FILE_FORMAT = "txt";
private static final String PDF_FILE_FORMAT = "pdf";
```

2018-01-16 18:45 UTC, sabaudragos approved these changes

2018-01-16 18:45 UTC, merged